# Todos los tests tienen que estar juntos para poder recompilarlos
# y hacer las pruebas automáticas. No meterlos en directorios diferentes.
# EJ: no crear alp/matrix/test <-- no se compilaría de forma automática
# al modificar alp.
DIRS = cast \
	container \
	exception \
	functional \
	geo_types \
	iterator \
	math \
	matrix \
	time \
	type_traits \
	vector3d

#	string \ <--- lo estaba modificando
#	trace \	???

include $(CPP_RECRULES)


