# Todos los tests tienen que estar juntos para poder recompilarlos
# y hacer las pruebas automáticas. No meterlos en directorios diferentes.
# EJ: no crear alp/matrix/test <-- no se compilaría de forma automática
# al modificar alp.
DIRS = cast 	\
	container 	\
	exception 	\
	functional 	\
	iterator 	\
	math 		\
	matrix 		\
	rframe_ij	\
	rframe_xyz	\
	time 		\
	type_traits \

#	rframe		\
#
#	string \ <--- lo estaba modificando
#	trace \	???

include $(CPP_RECRULES)


