SOURCES = main.cpp	\
		  ../../../alp_cerror.cpp	\
		  ../../../alp_exception.cpp	\
		  ../../../alp_termios_iostream.cpp	\
		  ../alp_termios_avr.cpp	\
		  ../../../alp_termios_cfg.cpp

BIN = xx


include $(ALP_COMPRULES)
