SOURCES=alp_cast.cpp 	\
	alp_cerror.cpp 		\
	alp_exception.cpp 	\
	alp_getopts.cpp		\
	alp_filesystem.cpp 	\
	alp_iso88591.cpp	\
	alp_math.cpp		\
	alp_rframe_ij.cpp 	\
	alp_stdio.cpp 		\
	alp_string.cpp		\
	alp_termios_cfg.cpp 	\
	alp_termios_iostream.cpp 	\
	alp_time.cpp 		\
	alp_trace.cpp 		\
	alp_utf8.cpp 		\
	alp_test.cpp


INCS= alp_algorithm.h 	\
	alp_array.h			\
	alp_cast.h 			\
	alp_cerror.h 		\
	alp_concepts.h 		\
	alp_statistics.h 	\
	alp_exception.h 	\
	alp_filesystem.h 	\
	alp_find.h 			\
	alp_functional.h	\
	alp_getopts.h		\
	alp_iso88591.h		\
	alp_istream.h		\
	alp_iterator.h 		\
	alp_math_efunc.h 	\
	alp_math.h 			\
	alp_matrix.h 		\
	alp_matrix_view.h 	\
	alp_matrix_algorithm.h 	\
	alp_matrix_iterator.h 	\
	alp_submatrix.h 	\
	alp_random.h 		\
	alp_rframes.h		\
	alp_rframe_ij.h 	\
	alp_rframe_xy.h 	\
	alp_rframe_xyz.h 	\
	alp_stdio.h 		\
	alp_string.h 		\
	alp_subcontainer.h 	\
	alp_test.h 			\
	alp_termios.h		\
	alp_termios_cfg.h 		\
	alp_termios_iostream.h 		\
	alp_time.h 			\
	alp_trace.h 		\
	alp_type_traits.h 	\
	alp_utf8.h 			\
	alp_vector.h	



LIB=alp

include $(ALP_COMPRULES)


#	alp_rels.h 			\
