SOURCES=alp_cast.cpp 	\
	alp_cerror.cpp 		\
	alp_exception.cpp 	\
	alp_getopts.cpp		\
	alp_filesystem.cpp 	\
	alp_stdio.cpp 		\
	alp_string.cpp		\
	alp_termios_avr.cpp 		\
	alp_termios_cfg.cpp 	\
	alp_termios_iostream.cpp 	\
	alp_time.cpp 		\
	alp_trace.cpp 		\
	alp_utf8.cpp 		\
	alp_test.cpp


INCS= alp_algorithm.h 	\
	alp_array.h			\
	alp_cast.h 			\
	alp_cerror.h 		\
	alp_concepts.h 		\
	alp_statistics.h 	\
	alp_exception.h 	\
	alp_filesystem.h 	\
	alp_find.h 			\
	alp_functional.h	\
	alp_gen.h 			\
	alp_geo_types.h 	\
	alp_getopts.h		\
	alp_indices.h 		\
	alp_iterator.h 		\
	alp_math_efunc.h 	\
	alp_math.h 			\
	matrix/alp_matrix.h 		\
	matrix/alp_matrix_view.h 	\
	matrix/alp_matrix_algorithm.h 	\
	matrix/alp_matrix_iterator.h 	\
	matrix/alp_submatrix.h 	\
	alp_random.h 		\
	alp_stdio.h 		\
	alp_string.h 		\
	alp_subcontainer.h 	\
	alp_test.h 			\
	alp_termios_avr.h 		\
	alp_termios_cfg.h 		\
	alp_termios_iostream.h 		\
	alp_time.h 			\
	alp_trace.h 		\
	alp_type_traits.h 	\
	alp_utf8.h 			\
	alp_vector.h		\
	alp_vector3D.h



LIB=alp

include $(ALP_COMPRULES)


#	alp_rels.h 			\
